### ISSUE TITLE
Undefined offset: 922 in /vendor/nemiah/php-fints/lib/Fhp/FinTs.php on line 466

### ISSUE THREAD

**Issue by bavarialogy** [bnw/firefly-iii-fints-importer#47] opened 2021-08-25 15:38 UTC
When entering the data for my bank account, this message appears twice above the "Choose a device for your tan method." selection:

`Notice: Undefined offset: 922 in /vendor/nemiah/php-fints/lib/Fhp/FinTs.php on line 466`

It doesn't matter if I create the configuration with a JSON file or if I enter the information manually. The data entered is:

`"bank_code": "71152570",
"bank_url": "https://banking-by2.s-fints-pt-by.de/fints30",
"bank_2fa": "921",`

Should I try to update the FinTs library first or is there an issue with the importer that may prevent me from getting my transactions?

Edit 1: Removed double quote
Edit 2: I do see the pushTAN devices registered for my account in the dropdown menu.

**Comment by jurgenhaas** [comment] 2021-11-23 07:15
I'm having the same issue but the proposed solution doesn't work for me.

**Comment by bnw** [comment] 2022-07-31 20:24
Should be fixed since [47177d0](https://github.com/bnw/firefly-iii-fints-importer/commit/47177d06457446ee750e52b9795dd17e032a27c4) :)

If not, please reopen.

**Closed by bnw** 2022-07-31 20:24 UTC

**Comment by jurgenhaas** [comment] 2022-08-01 06:47
Confirmed, this is now fixed. Thanks!
